### ISSUE TITLE
Unable to compile programs that use libfxcg functions in them.

### ISSUE THREAD

**Issue by EvanMad** [Jonimoose/libfxcg#53]
I've compiled some basic hello work programs and such, but was interested in drawing some sprites to the screen, so i defined by sprite data in code and tried to use `VRAM_CopySprite` to load up the sprite but i just get the error `undefined reference to _VRAM_CopySprite`. I've checked over my makefile (It's the default one) and it seems the library is getting included fine and i'm doing `#include <fxcg/display.h>` so I don't see why this issue is being caused. I would attach my full code but honestly not sure it's necessary, i'm just calling `VRAM_CopySprite(logo, 249, 25, 80, 58);` where `logo` is a whole bunch of color_t data.

Forgive me if this is basic or not appropriate for an issue, I'm new to github _and_ not really familiar with build systems all that much since my background is in python.

Thanks in advance, Evan.

**Comment by tari** [comment]
It's hard to guess what you might be doing wrong. Can you share the output when you try to build your program?

**Comment by EvanMad** [comment]
Hi sorry, forgot to get back to you on this, the error i got was `example.c:(.text.startup.main+0x48): undefined reference to `_VRAM_CopySprite'`

**Comment by tari** [comment]
That function should be defined, so your libraries seem to be incorrect in some way.

I'd expect it to be a public symbol in libfxcg.a, and it is in the release binaries we provide:
```
$ nm -g libfxcg-0.5.1-bin/lib/libfxcg.a | grep CopySprite
00000000 T _VRAM_CopySprite
```

Testing in the [`jonimoose/libfxcg-toolchain`](https://hub.docker.com/r/jonimoose/libfxcg-toolchain) docker image however (which should be more representative of the distribution tools), I get warnings about missing plugins when I use `nm`. I notice libfxcg is being built with LTO (`-flto`), so that's not entirely unexpected.

Taking the `skeleton` example and adding a call to `VRAM_CopySprite` to it however, I can reproduce the issue. With a reproducer, I have a few fixes for you:

* A quick fix you can take right now is to add `-flto` to both `CFLAGS` and `LDFLAGS` in your Makefile. This may generate better code all around (smaller and/or faster), but could also cause your code to stop working if it contains bugs that aren't exposed when less optimization happens. Long-term, I'd recommend turning this on and leaving it on.
* Rebuilding libfxcg with `-ffat-lto-objects` will make the libraries include both LTO and plain objects. Currently it only generates LTO objects so a linker that's not doing LTO won't find any symbols: **this is the actual bug**.

I'll fix up the build system to build fat objects (and probably enable LTO for other things) to fix the underlying problem.
